name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        pip install requests
        pip install mock
    - name: Run unit tests
      run: |
        python -m unittest tests/test_unit.py
    - name: Run integration tests
      run: |
        python -m unittest tests/test_integration.py
